src/BitLogic/BaseBundle/Form/ActivoType.php
<?php

/**
 * Description of FichaHiddenType
 *
 * @author Gabriel Toledo
 */

namespace BitLogic\BaseBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class ActivoType extends AbstractType{
    


    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'empty_value' => ' ',
            'empty_data' => null,
             'required' => false,
            'choices' => array(
                'S'=>'S',
                'N'=>'N',
            ),
        ));
    }

    public function getParent()
    {
        return 'choice';
    }

    public function getName()
    {
        return 'activo';
    }
}

src/BitLogic/BaseBundle/Form/FiltroHtmlType.php
<?php

namespace BitLogic\BaseBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class FiltroHtmlType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        
        $builder
            ->add('pagenum', 'number',array(
                //'mapped'=>false
            ))
            ->add('pagenum', 'number',array(
                'mapped'=>false
            ))
            ->add('pagesize', 'number',array(
                'mapped'=>false
            ))
            ->add('sortdatafield', 'text',array(
                'mapped'=>false
            ))
            ->add('sortorder', 'text',array(
                'mapped'=>false
            ))
            ->add('btnBuscar', 'submit',array(   
                'attr'=> array(
                         'class'=>'btn btn-default glyphicon glyphicon-search',
                         'data-toggle' => 'tooltip',
                         'data-placement'=> 'top',
                         'title'=> 'Buscar',
                          ),
                  'label'=>' ')
                  )
            ->setMethod('GET');

    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults([
            'data_class' => 'BitLogic\BaseBundle\Grilla\Grilla',
            'csrf_protection' => false,
        ]);
    }

    public function getName()
    {
        return 'filtroHtml';
    }
}

src/BitLogic/BaseBundle/Form/FiltroType.php
<?php

namespace BitLogic\BaseBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class FiltroType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('pagenum', 'number')
            ->add('pagenum', 'number')
            ->add('pagesize', 'number')
            ->add('sortdatafield', 'text')
            ->add('sortorder', 'text')
            ->setMethod('GET');

    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults([
            'data_class' => 'BitLogic\BaseBundle\Grilla\Grilla',
            'csrf_protection' => false,
        ]);
    }

    public function getName()
    {
        return 'filtro';
    }
}

src/BitLogic/BaseBundle/Form/MesesTxtType.php
<?php

/**
 * Description of FichaHiddenType
 *
 * @author Gabriel Toledo
 */

namespace BitLogic\BaseBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class MesesTxtType extends AbstractType{
    


    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'empty_value' => 'Seleccione mes',
            'choices' => array(
                'ENERO'=>'ENERO',
                'FEBRERO'=>'FEBRERO',
                'MARZO'=>'MARZO',
                'ABRIL'=>'ABRIL',
                'MAYO'=>'MAYO',
                'JUNIO'=>'JUNIO',
                'JULIO'=>'JULIO',
                'AGOSTO'=>'AGOSTO',
                'SEPTIEMBRE'=>'SEPTIEMBRE',
                'OCTUBRE'=>'OCTUBRE',
                'NOVIEMBRE'=>'NOVIEMBRE',
                'DICIEMBRE'=>'DICIEMBRE',
            ),
        ));
    }

    public function getParent()
    {
        return 'choice';
    }

    public function getName()
    {
        return 'meses_txt';
    }
}

src/BitLogic/BaseBundle/Form/SexoType.php
<?php

/**
 * Description of FichaHiddenType
 *
 * @author Gabriel Toledo
 */

namespace BitLogic\BaseBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class SexoType extends AbstractType{
    


    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'empty_value' => 'Seleccione Sexo',
            'empty_data' => null,
             'required' => false,
            'choices' => array(
                'M'=>'Maculino',
                'F'=>'Femenino',
            ),
        ));
    }

    public function getParent()
    {
        return 'choice';
    }

    public function getName()
    {
        return 'sexo';
    }
}

src/BitLogic/BaseBundle/Form/TipoDocType.php
<?php

/**
 * Description of FichaHiddenType
 *
 * @author Gabriel Toledo
 */

namespace BitLogic\BaseBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class TipoDocType extends AbstractType{
    


    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'empty_value' => 'Seleccione el tipo de documento',
            'empty_data' => null,
            'required' => false,
            'choices' => array(
                'DNI'=>'DNI',
                'LE'=>'LE',
                'LC'=>'LC',
                'CEDULA PROVINCIAL'=>'CEDULA PROVINCIAL',
                'CEDULA FEDERAL'=>'CEDULA FEDERAL',
                'PASAPORTE'=>'PASAPORTE',
            ),
        ));
    }

    public function getParent()
    {
        return 'choice';
    }

    public function getName()
    {
        return 'tipo_doc';
    }
}

src/BitLogic/BaseBundle/Controller/AvisosController.php
<?php

namespace BitLogic\BaseBundle\Controller;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;

/**
 * Sistema controller.
 *
 * @Route("/avisos")
 */
class AvisosController extends Controller
{
 

    
    
    /**
     * Muestra la pantalla de zona restringida.
     *
     * @Route("/no_autorizado", name="no_autorizado")
     * @Template()
     */
    public function noAutorizadoAction()
    {
        return array();
    }


}

src/BitLogic/BaseBundle/Controller/DefaultController.php
<?php

namespace BitLogic\BaseBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;

class DefaultController extends Controller
{
    /**
     * @Route("/hello/{name}")
     * @Template()
     */
    public function indexAction($name)
    {
        return array('name' => $name);
    }
}

src/BitLogic/BaseBundle/Tests/Controller/DefaultControllerTest.php
<?php

namespace BitLogic\BaseBundle\Tests\Controller;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class DefaultControllerTest extends WebTestCase
{
    public function testIndex()
    {
        $client = static::createClient();

        $crawler = $client->request('GET', '/hello/Fabien');

        $this->assertTrue($crawler->filter('html:contains("Hello Fabien")')->count() > 0);
    }
}

src/BitLogic/BaseBundle/Resources/views/Avisos/noAutorizado.html.twig
{% extends 'BaseBundle::layout.html.twig' %}

{%block titulo %}No Autorizado{%endblock %}

{%block contenido %}


<div class="panel-heading">
    <h4> 
        <span class="glyphicon glyphicon-remove"></span> Acceso Denegado
    </h4>
</div>    
<div style="font-size: 12px;">
    <br>
    <br>
    <div class="alert alert-danger text-center">
        <span class="glyphicon glyphicon-remove"></span>
        Ud. NO tiene permisos asignados para acceder a esta parte del sistema. <br>
        Si ud. cree que hay un error por favor comuniquese consulte con el Responsable.<br/>
        
        <a href="javascript:history.back(-1);" class = "btn btn-danger">
                   <span class = "glyphicon glyphicon-backward"> </span>   Volver 
               </a>
    </div>
    <br>
    <br>
</div>

{%endblock %}

src/BitLogic/BaseBundle/Resources/views/Default/index.html.twig
Hello {{ name }}!

src/BitLogic/BaseBundle/Resources/views/Form/form_div_layout.html.twig
{# Widgets #}

{% block form_widget %}
{% spaceless %}
    {% if compound %}
        {{ block('form_widget_compound') }}
    {% else %}
        {{ block('form_widget_simple') }}
    {% endif %}
{% endspaceless %}
{% endblock form_widget %}

{% block form_widget_simple %}
{% spaceless %}
    {% set type = type|default('text') %}
    <input type="{{ type }}" {{ block('widget_attributes') }} {% if value is not empty %}value="{{ value }}" {% endif %}/>
{% endspaceless %}
{% endblock form_widget_simple %}

{% block form_widget_compound %}
{% spaceless %}
    <div {{ block('widget_container_attributes') }}>
        {% if form.parent is empty %}
            {{ form_errors(form) }}
        {% endif %}
        {{ block('form_rows') }}
        {{ form_rest(form) }}
    </div>
{% endspaceless %}
{% endblock form_widget_compound %}

{% block collection_widget %}
{% spaceless %}
    {% if prototype is defined %}
        {% set attr = attr|merge({'data-prototype': form_row(prototype) }) %}
    {% endif %}
    {{ block('form_widget') }}
{% endspaceless %}
{% endblock collection_widget %}

{% block textarea_widget %}
{% spaceless %}
    <textarea {{ block('widget_attributes') }}>{{ value }}</textarea>
{% endspaceless %}
{% endblock textarea_widget %}

{% block choice_widget %}
{% spaceless %}
    {% if expanded %}
        {{ block('choice_widget_expanded') }}
    {% else %}
        {{ block('choice_widget_collapsed') }}
    {% endif %}
{% endspaceless %}
{% endblock choice_widget %}

{% block choice_widget_expanded %}
{% spaceless %}
{#    <div {{ block('widget_container_attributes') }}>
    {% for child in form %}
        {{ form_widget(child) }}
        {{ form_label(child) }}
    {% endfor %}
    </div>#}
    <ul {{ block('widget_container_attributes') }}>
    {% for child in form %}
        <li>{{ form_widget(child) }} - 
        {{ form_label(child) }} </li>
    {% endfor %}
    </ul>
{% endspaceless %}
{% endblock choice_widget_expanded %}

{% block choice_widget_collapsed %}
{% spaceless %}
    {% if required and empty_value is none and not empty_value_in_choices %}
        {% set required = false %}
    {% endif %}
    <select {{ block('widget_attributes') }}{% if multiple %} multiple="multiple"{% endif %} >
        {% if empty_value is not none %}
            <option value=""{% if required and value is empty %} selected="selected"{% endif %}>{{ empty_value|trans({}, translation_domain) }}</option>
        {% endif %}
        {% if preferred_choices|length > 0 %}
            {% set options = preferred_choices %}
            {{ block('choice_widget_options') }}
            {% if choices|length > 0 and separator is not none %}
                <option disabled="disabled">{{ separator }}</option>
            {% endif %}
        {% endif %}
        {% set options = choices %}
        {{ block('choice_widget_options') }}
    </select>
{% endspaceless %}
{% endblock choice_widget_collapsed %}

{% block choice_widget_options %}
{% spaceless %}
    {% for group_label, choice in options %}
        {% if choice is iterable %}
            <optgroup label="{{ group_label|trans({}, translation_domain) }}">
                {% set options = choice %}
                {{ block('choice_widget_options') }}
            </optgroup>
        {% else %}
            <option value="{{ choice.value }}"{% if choice is selectedchoice(value) %} selected="selected"{% endif %}>{{ choice.label|trans({}, translation_domain) }}</option>
        {% endif %}
    {% endfor %}
{% endspaceless %}
{% endblock choice_widget_options %}

{% block checkbox_widget %}
{% spaceless %}
    <input type="checkbox" {{ block('widget_attributes') }}{% if value is defined %} value="{{ value }}"{% endif %}{% if checked %} checked="checked"{% endif %} />
{% endspaceless %}
{% endblock checkbox_widget %}

{% block radio_widget %}
{% spaceless %}
    <input type="radio" {{ block('widget_attributes') }}{% if value is defined %} value="{{ value }}"{% endif %}{% if checked %} checked="checked"{% endif %} />
{% endspaceless %}
{% endblock radio_widget %}

{% block datetime_widget %}
{% spaceless %}
    {% if widget == 'single_text' %}
        {{ block('form_widget_simple') }}
    {% else %}
        <div {{ block('widget_container_attributes') }}>
            {{ form_errors(form.date) }}
            {{ form_errors(form.time) }}
            {{ form_widget(form.date) }}
            {{ form_widget(form.time) }}
        </div>
    {% endif %}
{% endspaceless %}
{% endblock datetime_widget %}

{% block date_widget %}
{% spaceless %}
    {% if widget == 'single_text' %}
        {{ block('form_widget_simple') }}
    {% else %}
        <div {{ block('widget_container_attributes') }}>
            {{ date_pattern|replace({
                '{{ year }}':  form_widget(form.year),
                '{{ month }}': form_widget(form.month),
                '{{ day }}':   form_widget(form.day),
            })|raw }}
        </div>
    {% endif %}
{% endspaceless %}
{% endblock date_widget %}

{% block time_widget %}
{% spaceless %}
    {% if widget == 'single_text' %}
        {{ block('form_widget_simple') }}
    {% else %}
        {% set vars = widget == 'text' ? { 'attr': { 'size': 1 }} : {} %}
        <div {{ block('widget_container_attributes') }}>
            {{ form_widget(form.hour, vars) }}{% if with_minutes %}:{{ form_widget(form.minute, vars) }}{% endif %}{% if with_seconds %}:{{ form_widget(form.second, vars) }}{% endif %}
        </div>
    {% endif %}
{% endspaceless %}
{% endblock time_widget %}

{% block number_widget %}
{% spaceless %}
    {# type="number" doesn't work with floats #}
    {% set type = type|default('text') %}
    {{ block('form_widget_simple') }}
{% endspaceless %}
{% endblock number_widget %}

{% block integer_widget %}
{% spaceless %}
    {% set type = type|default('number') %}
    {{ block('form_widget_simple') }}
{% endspaceless %}
{% endblock integer_widget %}

{% block money_widget %}
{% spaceless %}
    {{ money_pattern|replace({ '{{ widget }}': block('form_widget_simple') })|raw }}
{% endspaceless %}
{% endblock money_widget %}

{% block url_widget %}
{% spaceless %}
    {% set type = type|default('url') %}
    {{ block('form_widget_simple') }}
{% endspaceless %}
{% endblock url_widget %}

{% block search_widget %}
{% spaceless %}
    {% set type = type|default('search') %}
    {{ block('form_widget_simple') }}
{% endspaceless %}
{% endblock search_widget %}

{% block percent_widget %}
{% spaceless %}
    {% set type = type|default('text') %}
    {{ block('form_widget_simple') }} %
{% endspaceless %}
{% endblock percent_widget %}

{% block password_widget %}
{% spaceless %}
    {% set type = type|default('password') %}
    {{ block('form_widget_simple') }}
{% endspaceless %}
{% endblock password_widget %}

{% block hidden_widget %}
{% spaceless %}
    {% set type = type|default('hidden') %}
    {{ block('form_widget_simple') }}
{% endspaceless %}
{% endblock hidden_widget %}

{% block email_widget %}
{% spaceless %}
    {% set type = type|default('email') %}
    {{ block('form_widget_simple') }}
{% endspaceless %}
{% endblock email_widget %}

{% block button_widget %}
{% spaceless %}
    {% if label is empty %}
        {% set label = name|humanize %}
    {% endif %}
    <button type="{{ type|default('button') }}" {{ block('button_attributes') }}>{{ label|trans({}, translation_domain) }}</button>
{% endspaceless %}
{% endblock button_widget %}

{% block submit_widget %}
{% spaceless %}
    {% set type = type|default('submit') %}
    {{ block('button_widget') }}
{% endspaceless %}
{% endblock submit_widget %}

{% block reset_widget %}
{% spaceless %}
    {% set type = type|default('reset') %}
    {{ block('button_widget') }}
{% endspaceless %}
{% endblock reset_widget %}

{# Labels #}

{% block form_label %}
{% spaceless %}
    {% if label is not same as(false) %}
        {% if not compound %}
            {% set label_attr = label_attr|merge({'for': id}) %}
        {% endif %}
        {% if required %}
            {% set label_attr = label_attr|merge({'class': (label_attr.class|default('') ~ ' required')|trim}) %}
        {% endif %}
        {% if label is empty %}
            {% set label = name|humanize %}
        {% endif %}
        <label{% for attrname, attrvalue in label_attr %} {{ attrname }}="{{ attrvalue }}"{% endfor %}>{{ label|trans({}, translation_domain) }}</label>
    {% endif %}
{% endspaceless %}
{% endblock form_label %}

{% block button_label %}{% endblock %}

{# Rows #}

{% block repeated_row %}
{% spaceless %}
    {#
    No need to render the errors here, as all errors are mapped
    to the first child (see RepeatedTypeValidatorExtension).
    #}
    {{ block('form_rows') }}
{% endspaceless %}
{% endblock repeated_row %}

{% block form_row %}
{% spaceless %}
        <div class="row ">
            <div class="col-xs-2">
                {{ form_label(form) }}
            </div>
            <div class="col-xs-4">
            {{ form_errors(form) }}
            {{ form_widget(form) }}
            </div>
        </div>
        <br/>
{% endspaceless %}
{% endblock form_row %}

{% block button_row %}
{% spaceless %}
    <div>
        {{ form_widget(form) }}
    </div>
{% endspaceless %}
{% endblock button_row %}

{% block hidden_row %}
    {{ form_widget(form) }}
{% endblock hidden_row %}

{# Misc #}

{% block form %}
{% spaceless %}
    {{ form_start(form) }}
        {{ form_widget(form) }}
    {{ form_end(form) }}
{% endspaceless %}
{% endblock form %}

{% block form_start %}
{% spaceless %}
    {% set method = method|upper %}
    {% if method in ["GET", "POST"] %}
        {% set form_method = method %}
    {% else %}
        {% set form_method = "POST" %}
    {% endif %}
    <form method="{{ form_method|lower }}" action="{{ action }}"{% for attrname, attrvalue in attr %} {{ attrname }}="{{ attrvalue }}"{% endfor %}{% if multipart %} enctype="multipart/form-data"{% endif %}>
    {% if form_method != method %}
        <input type="hidden" name="_method" value="{{ method }}" />
    {% endif %}
{% endspaceless %}
{% endblock form_start %}

{% block form_end %}
{% spaceless %}
    {% if not render_rest is defined or render_rest %}
        {{ form_rest(form) }}
    {% endif %}
    </form>
{% endspaceless %}
{% endblock form_end %}

{% block form_enctype %}
{% spaceless %}
    {% if multipart %}enctype="multipart/form-data"{% endif %}
{% endspaceless %}
{% endblock form_enctype %}

{% block form_errors %}
{% spaceless %}
    {% if errors|length > 0 %}
    <ul>
        {% for error in errors %}
            <li>{{ error.message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
{% endspaceless %}
{% endblock form_errors %}

{% block form_rest %}
{% spaceless %}
    {% for child in form %}
        {% if not child.rendered %}
            {{ form_row(child) }}
        {% endif %}
    {% endfor %}
{% endspaceless %}
{% endblock form_rest %}

{# Support #}

{% block form_rows %}
{% spaceless %}
    {% for child in form %}
        {{ form_row(child) }}
    {% endfor %}
{% endspaceless %}
{% endblock form_rows %}

{% block widget_attributes %}
{% spaceless %}
    id="{{ id }}" name="{{ full_name }}"{% if read_only %} readonly="readonly"{% endif %}{% if disabled %} disabled="disabled"{% endif %}{% if required %} required="required"{% endif %}{% if max_length %} maxlength="{{ max_length }}"{% endif %}{% if pattern %} pattern="{{ pattern }}"{% endif %}
    {% for attrname, attrvalue in attr %}{% if attrname in ['placeholder', 'title'] %}{{ attrname }}="{{ attrvalue|trans({}, translation_domain) }}" {% else %}{{ attrname }}="{{ attrvalue }}" {% endif %}{% endfor %}
{% endspaceless %}
{% endblock widget_attributes %}

{% block widget_container_attributes %}
{% spaceless %}
    {% if id is not empty %}id="{{ id }}" {% endif %}
    {% for attrname, attrvalue in attr %}{{ attrname }}="{{ attrvalue }}" {% endfor %}
{% endspaceless %}
{% endblock widget_container_attributes %}

{% block button_attributes %}
{% spaceless %}
    id="{{ id }}" name="{{ full_name }}"{% if disabled %} disabled="disabled"{% endif %}
    {% for attrname, attrvalue in attr %}{{ attrname }}="{{ attrvalue }}" {% endfor %}
{% endspaceless %}
{% endblock button_attributes %}

src/BitLogic/BaseBundle/Resources/views/Form/form_filter_layout.html.twig
{% use "BaseBundle:Form:form_div_layout.html.twig" %}

{% block form_row %}
{% spaceless %}
        <div class="row ">
            <div class="col-md-2">
                {{ form_label(form) }}
            </div>
            <div class="col-md-10">
            {{ form_errors(form) }}
            {{ form_widget(form) }}
            </div>
        </div>
        <br/>
{% endspaceless %}
{% endblock form_row %}

src/BitLogic/BaseBundle/Resources/views/Form/form_table_horizontal_layout.html.twig
{% use "form_div_layout.html.twig" %}

{% block form_row %}
{% spaceless %}

        <td>
            {{ form_errors(form) }}
            {{ form_widget(form) }}
        </td>

{% endspaceless %}
{% endblock form_row %}

{% block button_row %}
{% spaceless %}
    <tr>
        <td></td>
        <td>
            {{ form_widget(form) }}
        </td>
    </tr>
{% endspaceless %}
{% endblock button_row %}

{% block hidden_row %}
{% spaceless %}

   <td colspan="2" style="display: none">
    {{ form_widget(form) }}
   </td>

        
{% endspaceless %}
{% endblock hidden_row %}

{% block form_widget_compound %}
{% spaceless %}
    <table {{ block('widget_container_attributes') }}>
        {% if form.parent is empty and errors|length > 0 %}
        <tr>
            <td colspan="2">
                {{ form_errors(form) }}
            </td>
        </tr>
        {% endif %}
        <tr>
        {{ block('form_rows') }}
        </tr>
        {{ form_rest(form) }}
    </table>
{% endspaceless %}
{% endblock form_widget_compound %}

src/BitLogic/BaseBundle/Resources/views/Form/form_table_layout.html.twig
{% use "BaseBundle:Form:form_div_layout.html.twig" %}

{% block form_row %}
{% spaceless %}
    <tr>
        <td>
            {{ form_label(form) }}
        </td>
        <td>
            {{ form_errors(form) }}
            {{ form_widget(form) }}
        </td>
    </tr>
{% endspaceless %}
{% endblock form_row %}

{% block button_row %}
{% spaceless %}
    <tr>
        <td></td>
        <td>
            {{ form_widget(form) }}
        </td>
    </tr>
{% endspaceless %}
{% endblock button_row %}

{% block hidden_row %}
{% spaceless %}
    <tr style="display: none">
        <td colspan="2">
            {{ form_widget(form) }}
        </td>
    </tr>
{% endspaceless %}
{% endblock hidden_row %}

{% block form_widget_compound %}
{% spaceless %}
    <table {{ block('widget_container_attributes') }}class="table table-responsive">
        {% if form.parent is empty and errors|length > 0 %}
        <tr>
            <td colspan="2">
                {{ form_errors(form) }}
            </td>
        </tr>
        {% endif %}
        {{ block('form_rows') }}
        {{ form_rest(form) }}
    </table>
{% endspaceless %}
{% endblock form_widget_compound %}

src/BitLogic/BaseBundle/Resources/views/Form/form_table_layout_horizontal.html.twig
{% use "form_div_layout.html.twig" %}

{% block form_row %}
{% spaceless %}
        <td>
            {{ form_errors(form) }}
            {{ form_widget(form) }}
        </td>
{% endspaceless %}
{% endblock form_row %}

{% block button_row %}
{% spaceless %}
    <tr>
        <td></td>
        <td>
            {{ form_widget(form) }}
        </td>
    </tr>
{% endspaceless %}
{% endblock button_row %}

{% block hidden_row %}
{% spaceless %}
    <tr style="display: none">
        <td colspan="2">
            {{ form_widget(form) }}
        </td>
    </tr>
{% endspaceless %}
{% endblock hidden_row %}

{% block form_widget_compound %}
{% spaceless %}
    <table {{ block('widget_container_attributes') }}>
        {% if form.parent is empty and errors|length > 0 %}
        <tr>
            <td colspan="5">
                {{ form_errors(form) }}
            </td>
        </tr>
        {% endif %}
        <tr>
            {{ block('form_rows') }}
        </tr>
        {{ form_rest(form) }}
    </table>
{% endspaceless %}
{% endblock form_widget_compound %}

src/BitLogic/BaseBundle/Resources/views/Menu/menu_empleados.html.twig
<nav class="navbar navbar-inverse "  role="navigation">
    
    
        <div class="container-fluid" >
            <div class="navbar-header">

                <button class="navbar-toggle " data-target=".navbar-collapse" data-toggle="collapse" type="button">
                    <span class="sr-only">Navegación Expandible</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="glyphicon glyphicon-list"></span>
                </button>

            </div>
        </div>
        <div class="collapse navbar-collapse ">           
            <ul class="nav navbar-nav">

                <li class='has-sub '>
                    <a href="{{ path('turno_consola') }}"><span>Turnos</span></a>
                </li>
                <li class='has-sub '>
                    <a href="{{ path('rendicion_turnos') }}"><span>Rendición</span></a>
                </li>                
                

            </ul>
        </div>
</nav>

                
        
        
       

src/BitLogic/BaseBundle/Resources/views/Pagination/filtration.html.twig
<form method="get" action="{{ action }}" enctype="application/x-www-form-urlencoded">

    <select name="{{ filterFieldName }}">
        {% for field, label in fields %}
            <option value="{{ field }}"{% if selectedField == field %} selected="selected"{% endif %}>{{ label }}</option>
        {% endfor %}
    </select>

    <input type="text" value="{{ selectedValue }}" name="{{ filterValueName }}" />

    <button>{{ options.button }}</button>

</form>

src/BitLogic/BaseBundle/Resources/views/Pagination/sliding.html.twig
{# default Sliding pagination control implementation #}

{% if pageCount > 1 %}
<div class="pagination">
    {% if first is defined and current != first %}
        <span class="first">
            <a href="{{ path(route, query|merge({(pageParameterName): first})) }}">&lt;&lt;</a>
        </span>
    {% endif %}

    {% if previous is defined %}
        <span class="previous">
            <a href="{{ path(route, query|merge({(pageParameterName): previous})) }}">&lt;</a>
        </span>
    {% endif %}

    {% for page in pagesInRange %}
        {% if page != current %}
            <span class="page">
                <a href="{{ path(route, query|merge({(pageParameterName): page})) }}">{{ page }}</a>
            </span>
        {% else %}
            <span class="current">{{ page }}</span>
        {% endif %}

    {% endfor %}

    {% if next is defined %}
        <span class="next">
            <a href="{{ path(route, query|merge({(pageParameterName): next})) }}">&gt;</a>
        </span>
    {% endif %}

    {% if last is defined and current != last %}
        <span class="last">
            <a href="{{ path(route, query|merge({(pageParameterName): last})) }}">&gt;&gt;</a>
        </span>
    {% endif %}
</div>
{% endif %}

src/BitLogic/BaseBundle/Resources/views/Pagination/sortable_link.html.twig
<a{% for attr, value in options %} {{ attr }}="{{ value }}"{% endfor %}>{{ title }}</a>